language: ruby
rvm:
- 2.3.3
cache: bundler
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: faKZX/PfyTp62i/gqo5Y64gBlfmyqVuM44v6JuR1Pbj0m1pmIQgcMYuOkiBKPXK768mLPpyuJnr/HUpwvANj6Ar1dNkhz+59OaiPo1+MGBjeDe7cbW7lFojq59G4uNaTq9ZHfDqoec9dFQLD0OglrprF9NB/aKliwmzxzogsjcrnMOWjszIw+98bo7bqcJkDD+VsHvOUniY0mCLADFuleve3ALmIFNdGBMwCexqu5W94mdsL/TE79qKHoKYf10Ul3mzrPUCOC7ixUx9t8+bNf4I0G2KRLBpzqcyvQ7FcnK38mFjA5By4eoY8p+NaREINiwDZszMY3Up8VbNXbLXTAYPX3TMcWfOwgPtmz9B7LXuxcJu+0AFmuX6yq8nTMDBevh0Qq64nlOPV2tvNI4TokrwmJl9UKevlaBtewRIAo71CHrLRwAH0ibhCqI6UxyP9GhLXDesRG2YrKky/NaiZwLXwG3fwHXKvDj7vpbGDXFtINyaSoG6gLBYv6hBUZo1UzzQ/1vdNNavtmZK5bWW7Lpfp8D4/iDgm/cdLEDRFnA5YbF7gtZwImOP5x3Yo68ipv9McH1FjxXreHaEqHU01Dg9kEnmv6RCmNlImvj39U/Hx4ViXdZTJ7iKNkUEQtABIETNE7+1TcXH/+RlAbx3RqknA8ixdpFOTR1NP4vqVnYI=
  app: blog-ryanlabouve-api
  on:
    repo: ryanlabouve/com-ryanlabouve-api
script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake test
notifications:
  slack:
    secure: Xnwuje/rst/02ZjOp72uJVPNp8v2YLlSEHp2ZQ9hVyfb+nuPH03+erNByrekMd+w0OVPV4t6ZQ56+wPNpD0p5HoTuVlc4FbG4MaT53hV9EXJlXcj6uthaPgk5VgdBop0ppkU5xrkQQJTaukh21LFHyAzb+A1Hk052LLipQawdxcFZ0e3mdvqMYcv/K58O8SzraQ4Uf4Aag/uQNx3k+7taW8tBDPG2MgppeOyeELaK51RA/nkHuiJoS234FkRE/54W1Rr+sFZ68gA3ARtOvb2PJakplEKqgBYEqogALOD9d/98Gpxnd9XwXM2TfvIf6lle6Dwy2dNTCSU0l17RZ/61QwbmXbBO6MLZQwNx7YdqL19U/BveoXMWaBI/xXULkD1TZCw2SbiBB9exuqXfIa1cThSjru8dNCPGogSxjKkXp+rhNz3Q2PYi4vmio8tVAdC3LsvmJaOW5PK73Y9/rPZkSCRqmFGKntEAdbOJa6jJCRkW34Fo7dtLBt2slIIu3Q1mvnJjMV35x8Jslhc+Ir8jOAU5hMqVkjLC9SMCV4+8bN/v92klmdrAzuF7aZz+HSLpvmf4hm3Ex6HQ+XtpzN2ZUCXiuKaDwy+PxoDguEz6CriW7LkBVgJr565zTZl1v3MGCIuiDTnbgeGrPfhKPgj10bAOpl9cVOfFlkn0U+Su0A=
